// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1eh_2msZTJ1hE0gV_nZb_1rkn5Xcbb4E',
    appId: '1:939849111238:web:dc0c2af7f815e82874a9c7',
    messagingSenderId: '939849111238',
    projectId: 'notix-2a315',
    authDomain: 'notix-2a315.firebaseapp.com',
    storageBucket: 'notix-2a315.firebasestorage.app',
    measurementId: 'G-T6FJ466M6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqRPdrSIPAfIumyWfgNHp-Pg6HAOSlY2s',
    appId: '1:939849111238:android:5cb0e506815ad70674a9c7',
    messagingSenderId: '939849111238',
    projectId: 'notix-2a315',
    storageBucket: 'notix-2a315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_SRKQlDaUnylo7NwT2aK0dtFNjkY50do',
    appId: '1:939849111238:ios:10d24aa2198bd14874a9c7',
    messagingSenderId: '939849111238',
    projectId: 'notix-2a315',
    storageBucket: 'notix-2a315.firebasestorage.app',
    iosBundleId: 'com.example.studentNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_SRKQlDaUnylo7NwT2aK0dtFNjkY50do',
    appId: '1:939849111238:ios:10d24aa2198bd14874a9c7',
    messagingSenderId: '939849111238',
    projectId: 'notix-2a315',
    storageBucket: 'notix-2a315.firebasestorage.app',
    iosBundleId: 'com.example.studentNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1eh_2msZTJ1hE0gV_nZb_1rkn5Xcbb4E',
    appId: '1:939849111238:web:f2d8e08585d6c69074a9c7',
    messagingSenderId: '939849111238',
    projectId: 'notix-2a315',
    authDomain: 'notix-2a315.firebaseapp.com',
    storageBucket: 'notix-2a315.firebasestorage.app',
    measurementId: 'G-1S6JX9MY6J',
  );
}
